server:
  port: 8765
documentation:
  swagger:
    services:
#    -
#      name: Auth Service
#      url: http://10.3.1.152:9001/v2/api-docs
#      version: 2.0
    -
      name: Human Service
      url: http://petstore.swagger.io/v2/swagger.json
      version: 2.0
    -
      name: Zoo Service
      url: http://petstore.swagger.io/v2/swagger.json
      version: 2.0
    -
      name: Food Service
      url: http://petstore.swagger.io/v2/swagger.json
      version: 2.0